person:
  age: 18
  boss: false
  birth: 2018/02/09
  maps:
    k1: v1
    k2: 18
  lists:
    - lisi
    - zhaoliu
  last-name: xiaoliu
spring:
  messages:
    basename: i18n.login

  thymeleaf:
    cache: false
logging:
  pattern:
    console: 【%thread】  %-5level [%logger{50}] %msg %n